#!/bin/bash
#-------------------------------------------------------------------
# X initialization specific to Xmonad.
#-------------------------------------------------------------------

# Start polybar on every monitor
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload xmonad &
  done
else
  polybar --reload xmonad &
fi
