#!/bin/bash

#-------------------------------------------------------------------
# Add fonts from /usr/share/fonts/local to the font cache.
#-------------------------------------------------------------------
xset +fp /usr/share/fonts/local
xset fp rehash

